[gui_graphics]
type = "regex"
condition = "< 26.1"
regex = "import net.minecraft.client.gui.GuiGraphicsExtractor(?!;)"
to = "import net.minecraft.client.gui.GuiGraphics as GuiGraphicsExtractor"
reverseRegex = "import net.minecraft.client.gui.GuiGraphics as GuiGraphicsExtractor"
reverse = "import net.minecraft.client.gui.GuiGraphicsExtractor"
